name: test-action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint-fix
